### ISSUE TITLE
QUERY: any ideas

### ISSUE THREAD

**Issue by mrose17** [jasontbradshaw/irobot#3]
this is rather odd. when i run test2.js talking to the roowifi, it seems that the motive commands are ignored. i've tried both drive and demo mouse, and nothing happens. the sound plays, so i'm thinking that something must be working. could you just eyeball this and tell me if anything stands out?

thanks!

node test2.js 
{ name: 'start', opcode: 128, bytes: 0 }
<Buffer 80>
{ name: 'safe', opcode: 131, bytes: 0 }
<Buffer 83>
{ name: 'leds', opcode: 139, bytes: 3 }
<Buffer 8b 00 00 00>
{ name: 'leds', opcode: 139, bytes: 3 }
<Buffer 8b 00 00 ff>
{ name: 'song', opcode: 140, bytes: null }
<Buffer 8c 00 02 4b 06 4c 06>
{ name: 'play_song', opcode: 141, bytes: 1 }
<Buffer 8d 00>
READY
{ name: 'demo', opcode: 136, bytes: 1 }
<Buffer 88 03>

**Comment by jasontbradshaw** [comment]
Try toggling the power on the robot. Occasionally, mine would do something similar, I suspect waiting for an unfinished command of some sort.

Barring that though, I don't see anything out of the ordinary.

**Comment by mrose17** [comment]
thanks. i figured out what's going on, and am now implementing it. briefly: i was mistaken in thinking that i had to close the command connection to do an HTTP GET for the sensor data. that's not right. i need to keep it open, but i shouldn't use it while HTTP is active (and vice-versa).
